server:
  port: 8500
#eureka:
#  client:
#    service-url:
#      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
#      defaultZone: http://root:booszy@localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    #可能比较长，复制的时候请写在一行
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#    appname: springcloud-config-server
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址 .git可加可不加
          uri: https://github.com/xiyimiao/config-server.git
          username: 765296872@qq.com
          password: 765296872.l
          #配置仓库路径 –这里写成’{profile}’是为了能让后面的服务在不同环境下动态的去获得相对应的目录下的配置环境
          searchPaths: '{profile}'
security:
  basic:
    enabled: true
  user:
    #这是config-server的用户名和密码
    name: root
    password: 1234